services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
volumes:
  db:
